#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: rack-cache-test
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  app: rack-cache-test
  config: &default
    BUNDLE_WITHOUT: "development:test"

demo:
  app: rack-cache-test
  config: *default
